/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "design.sv:3.1-309.10" *)
module conv2d_mem(clk, rst, start, done, image_addr, image_addr_valid, image_addr_ready, image_r_data, image_g_data, image_b_data, image_data_valid, image_data_ready, kernel_addr, kernel_addr_valid, kernel_addr_ready, kernel_data, kernel_data_valid, kernel_data_ready, bias_addr, bias_addr_valid, bias_addr_ready
, bias_data, bias_data_valid, bias_data_ready, out_data, out_valid);
  (* src = "design.sv:98.5-308.8" *)
  wire [63:0] _000_;
  (* src = "design.sv:98.5-308.8" *)
  wire _001_;
  (* src = "design.sv:98.5-308.8" *)
  wire _002_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _003_;
  (* src = "design.sv:98.5-308.8" *)
  wire _004_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _005_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _006_;
  (* src = "design.sv:98.5-308.8" *)
  wire _007_;
  (* src = "design.sv:98.5-308.8" *)
  wire _008_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _009_;
  (* src = "design.sv:98.5-308.8" *)
  wire _010_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _011_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _012_;
  (* src = "design.sv:98.5-308.8" *)
  wire _013_;
  (* src = "design.sv:98.5-308.8" *)
  wire [5:0] _014_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _015_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _016_;
  (* src = "design.sv:98.5-308.8" *)
  wire [31:0] _017_;
  (* src = "design.sv:98.5-308.8" *)
  wire [7:0] _018_;
  (* src = "design.sv:170.28-170.33" *)
  wire [31:0] _019_;
  (* src = "design.sv:171.28-171.33" *)
  wire [31:0] _020_;
  (* src = "design.sv:176.45-176.64" *)
  (* unused_bits = "10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _021_;
  (* src = "design.sv:192.39-192.70" *)
  wire [31:0] _022_;
  (* src = "design.sv:192.39-192.74" *)
  (* unused_bits = "28 29 30 31" *)
  wire [31:0] _023_;
  (* src = "design.sv:193.40-193.64" *)
  (* unused_bits = "9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _024_;
  (* src = "design.sv:223.39-223.57" *)
  wire [63:0] _025_;
  (* src = "design.sv:226.25-226.30" *)
  wire [31:0] _026_;
  (* src = "design.sv:231.29-231.34" *)
  wire [31:0] _027_;
  (* src = "design.sv:236.33-236.38" *)
  wire [31:0] _028_;
  (* src = "design.sv:251.40-251.67" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63" *)
  wire [63:0] _029_;
  (* src = "design.sv:253.42-253.70" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [63:0] _030_;
  (* src = "design.sv:254.35-254.51" *)
  wire [31:0] _031_;
  (* src = "design.sv:276.25-276.30" *)
  wire [31:0] _032_;
  (* src = "design.sv:281.29-281.34" *)
  wire [31:0] _033_;
  (* src = "design.sv:292.25-292.30" *)
  wire [31:0] _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  (* src = "design.sv:172.74-172.87" *)
  wire _069_;
  (* src = "design.sv:172.40-172.54" *)
  wire _070_;
  (* src = "design.sv:250.29-250.43" *)
  wire _071_;
  (* src = "design.sv:172.25-172.69" *)
  wire _072_;
  (* src = "design.sv:172.25-172.88" *)
  wire _073_;
  (* src = "design.sv:172.25-172.55" *)
  wire _074_;
  (* src = "design.sv:172.26-172.34" *)
  wire _075_;
  (* src = "design.sv:172.60-172.68" *)
  wire _076_;
  (* src = "design.sv:226.25-226.41" *)
  wire _077_;
  (* src = "design.sv:231.29-231.38" *)
  wire _078_;
  (* src = "design.sv:236.33-236.42" *)
  wire _079_;
  (* src = "design.sv:263.25-263.36" *)
  wire _080_;
  (* src = "design.sv:276.25-276.38" *)
  wire _081_;
  (* src = "design.sv:281.29-281.43" *)
  wire _082_;
  (* src = "design.sv:292.25-292.40" *)
  wire _083_;
  (* src = "design.sv:176.45-176.57" *)
  wire [31:0] _084_;
  (* src = "design.sv:192.39-192.44" *)
  wire [31:0] _085_;
  (* src = "design.sv:192.39-192.55" *)
  wire [31:0] _086_;
  (* src = "design.sv:192.58-192.70" *)
  wire [31:0] _087_;
  (* src = "design.sv:222.38-222.57" *)
  wire [47:0] _088_;
  (* src = "design.sv:251.41-251.56" *)
  wire [63:0] _089_;
  (* src = "design.sv:253.43-253.59" *)
  wire [63:0] _090_;
  (* src = "design.sv:253.43-253.53" *)
  wire [63:0] _091_;
  (* src = "design.sv:253.39-253.79" *)
  (* unused_bits = "32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63" *)
  wire [63:0] _092_;
  wire [7:0] _093_;
  wire _094_;
  wire _095_;
  wire [7:0] _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire [5:0] _109_;
  wire _110_;
  wire [5:0] _111_;
  wire [5:0] _112_;
  wire _113_;
  wire [5:0] _114_;
  wire [5:0] _115_;
  wire [5:0] _116_;
  wire [5:0] _117_;
  wire [5:0] _118_;
  wire [5:0] _119_;
  wire [5:0] _120_;
  wire [5:0] _121_;
  wire _122_;
  wire [5:0] _123_;
  wire [5:0] _124_;
  wire [5:0] _125_;
  wire _126_;
  wire [63:0] _127_;
  wire [31:0] _128_;
  wire [31:0] _129_;
  wire [31:0] _130_;
  wire [31:0] _131_;
  wire [31:0] _132_;
  wire [31:0] _133_;
  wire [31:0] _134_;
  wire [31:0] _135_;
  wire [31:0] _136_;
  wire [31:0] _137_;
  wire [31:0] _138_;
  wire [31:0] _139_;
  (* src = "design.sv:170.28-170.39" *)
  wire [31:0] _140_;
  (* src = "design.sv:171.28-171.39" *)
  wire [31:0] _141_;
  (* src = "design.sv:59.24-59.29" *)
  reg [63:0] accum;
  (* src = "design.sv:67.24-67.30" *)
  reg [15:0] bias16;
  (* src = "design.sv:36.23-36.32" *)
  output [3:0] bias_addr;
  reg [3:0] bias_addr;
  (* src = "design.sv:38.23-38.38" *)
  input bias_addr_ready;
  wire bias_addr_ready;
  (* src = "design.sv:37.23-37.38" *)
  output bias_addr_valid;
  reg bias_addr_valid;
  (* src = "design.sv:39.23-39.32" *)
  input [7:0] bias_data;
  wire [7:0] bias_data;
  (* src = "design.sv:41.23-41.38" *)
  output bias_data_ready;
  reg bias_data_ready;
  (* src = "design.sv:40.23-40.38" *)
  input bias_data_valid;
  wire bias_data_valid;
  (* src = "design.sv:52.19-52.20" *)
  reg [31:0] c;
  (* src = "design.sv:12.17-12.20" *)
  input clk;
  wire clk;
  (* src = "design.sv:15.17-15.21" *)
  output done;
  reg done;
  (* src = "design.sv:51.13-51.14" *)
  reg [31:0] f;
  (* src = "design.sv:51.16-51.17" *)
  reg [31:0] i;
  (* src = "design.sv:18.23-18.33" *)
  output [9:0] image_addr;
  reg [9:0] image_addr;
  (* src = "design.sv:20.23-20.39" *)
  input image_addr_ready;
  wire image_addr_ready;
  (* src = "design.sv:19.23-19.39" *)
  output image_addr_valid;
  reg image_addr_valid;
  (* src = "design.sv:23.23-23.35" *)
  input [7:0] image_b_data;
  wire [7:0] image_b_data;
  (* src = "design.sv:70.37-70.46" *)
  reg [7:0] image_b_q;
  (* src = "design.sv:25.23-25.39" *)
  output image_data_ready;
  reg image_data_ready;
  (* src = "design.sv:24.23-24.39" *)
  input image_data_valid;
  wire image_data_valid;
  (* src = "design.sv:22.23-22.35" *)
  input [7:0] image_g_data;
  wire [7:0] image_g_data;
  (* src = "design.sv:70.26-70.35" *)
  reg [7:0] image_g_q;
  (* src = "design.sv:21.23-21.35" *)
  input [7:0] image_r_data;
  wire [7:0] image_r_data;
  (* src = "design.sv:70.15-70.24" *)
  reg [7:0] image_r_q;
  (* src = "design.sv:51.19-51.20" *)
  reg [31:0] j;
  (* src = "design.sv:28.23-28.34" *)
  output [8:0] kernel_addr;
  reg [8:0] kernel_addr;
  (* src = "design.sv:30.23-30.40" *)
  input kernel_addr_ready;
  wire kernel_addr_ready;
  (* src = "design.sv:29.23-29.40" *)
  output kernel_addr_valid;
  wire kernel_addr_valid;
  (* src = "design.sv:31.23-31.34" *)
  input [7:0] kernel_data;
  wire [7:0] kernel_data;
  (* src = "design.sv:33.23-33.40" *)
  output kernel_data_ready;
  reg kernel_data_ready;
  (* src = "design.sv:32.23-32.40" *)
  input kernel_data_valid;
  wire kernel_data_valid;
  (* src = "design.sv:71.15-71.23" *)
  reg [7:0] kernel_q;
  (* src = "design.sv:52.13-52.14" *)
  reg [31:0] m;
  (* src = "design.sv:52.16-52.17" *)
  reg [31:0] n;
  (* src = "design.sv:44.24-44.32" *)
  output [31:0] out_data;
  reg [31:0] out_data;
  (* src = "design.sv:45.24-45.33" *)
  output out_valid;
  reg out_valid;
  (* src = "design.sv:13.17-13.20" *)
  input rst;
  wire rst;
  (* src = "design.sv:14.17-14.22" *)
  input start;
  wire start;
  (* src = "design.sv:77.15-77.20" *)
  reg [5:0] state;
  assign _021_ = $signed({ _084_[31:5], 5'h00 }) + (* src = "design.sv:176.45-176.64" *) $signed(_141_);
  assign _022_ = $signed(_086_) + (* src = "design.sv:192.39-192.70" *) $signed(_087_);
  assign _023_ = $signed(_022_) + (* src = "design.sv:192.39-192.74" *) $signed(c);
  assign _024_ = $signed({ _023_[27:0], 4'h0 }) + (* src = "design.sv:193.40-193.64" *) $signed(f);
  assign _019_ = $signed(i) + (* src = "design.sv:212.28-212.33" *) $signed(m);
  assign _020_ = $signed(j) + (* src = "design.sv:213.28-213.33" *) $signed(n);
  assign _025_ = $signed(accum) + (* src = "design.sv:223.39-223.57" *) $signed(_088_);
  assign _026_ = $signed(c) + (* src = "design.sv:227.30-227.35" *) $signed(32'd1);
  assign _027_ = $signed(n) + (* src = "design.sv:232.34-232.39" *) $signed(32'd1);
  assign _028_ = $signed(m) + (* src = "design.sv:237.38-237.43" *) $signed(32'd1);
  assign _029_ = $signed(_089_) + (* src = "design.sv:251.40-251.67" *) $signed(64'h0000000000008000);
  assign _030_ = $signed(_090_) + (* src = "design.sv:253.42-253.70" *) $signed(64'h0000000000008000);
  assign _031_ = $signed(_017_) + (* src = "design.sv:254.35-254.51" *) $signed(bias16);
  assign _032_ = $signed(j) + (* src = "design.sv:277.30-277.35" *) $signed(32'd1);
  assign _033_ = $signed(i) + (* src = "design.sv:282.34-282.39" *) $signed(32'd1);
  assign _034_ = $signed(f) + (* src = "design.sv:293.30-293.35" *) $signed(32'd1);
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk)
    if (_054_) image_g_q <= image_g_data;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk)
    if (_054_) image_r_q <= image_r_data;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk)
    if (_055_) kernel_q <= kernel_data;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk)
    if (_054_) image_b_q <= image_b_data;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 6'h00;
    else if (_056_) state <= _014_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk)
    if (_057_) bias16 <= { bias_data[7], bias_data[7], bias_data[7], bias_data[7], bias_data[7], bias_data[7], bias_data[7], bias_data[7], bias_data };
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else if (_043_) done <= _004_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) image_addr <= 10'h000;
    else if (_058_) image_addr <= _021_[9:0];
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) kernel_addr <= 9'h000;
    else if (_059_) kernel_addr <= _024_[8:0];
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) bias_addr <= 4'h0;
    else if (_103_) bias_addr <= f[3:0];
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) out_data <= 32'd0;
    else if (_099_) out_data <= _016_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) out_valid <= 1'h0;
    else if (_044_) out_valid <= _013_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) f <= 32'd0;
    else if (_060_) f <= _005_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) i <= 32'd0;
    else if (_061_) i <= _006_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) j <= 32'd0;
    else if (_062_) j <= _009_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) m <= 32'd0;
    else if (_063_) m <= _011_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) n <= 32'd0;
    else if (_064_) n <= _012_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) c <= 32'd0;
    else if (_052_) c <= _003_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) accum <= 64'h0000000000000000;
    else if (_065_) accum <= _000_;
  assign _035_ = { _126_, start } != 2'h2;
  assign _036_ = { _100_, _073_, image_addr_ready } != 3'h4;
  assign _037_ = { _098_, image_data_valid } != 2'h2;
  assign _038_ = { _098_, kernel_addr_ready, image_data_valid } != 3'h5;
  assign _039_ = { _105_, kernel_data_valid } != 2'h2;
  assign _040_ = { _103_, bias_addr_ready } != 2'h2;
  assign _041_ = { _102_, bias_data_valid } != 2'h2;
  assign _042_ = ~ _108_;
  assign _043_ = | { _126_, _108_ };
  assign _044_ = | { _099_, _066_ };
  assign _045_ = { _110_, _083_ } != 2'h2;
  assign _046_ = | { _126_, _110_ };
  assign _047_ = { _113_, _081_ } != 2'h3;
  assign _048_ = | { _126_, _113_ };
  assign _049_ = { _097_, _079_, _078_, _077_ } != 4'h8;
  assign _050_ = { _097_, _078_, _077_ } != 3'h6;
  assign _051_ = { _097_, _077_ } != 2'h3;
  assign _052_ = | { _122_, _097_ };
  assign _053_ = { _097_, _073_ } != 2'h3;
  assign _067_ = ~ rst;
  assign _068_ = ~ _073_;
  assign _054_ = & { _067_, _098_, image_data_valid };
  assign _055_ = & { _067_, _105_, kernel_data_valid };
  assign _056_ = & { _042_, _041_, _040_, _039_, _038_, _037_, _036_, _035_ };
  assign _057_ = & { _067_, _102_, bias_data_valid };
  assign _058_ = & { _068_, _100_ };
  assign _059_ = & { _098_, image_data_valid };
  assign _060_ = & { _046_, _045_, _035_ };
  assign _061_ = & { _048_, _047_, _035_ };
  assign _062_ = & { _048_, _035_ };
  assign _063_ = & { _051_, _050_, _049_, _052_ };
  assign _064_ = & { _051_, _052_ };
  assign _065_ = & { _053_, _052_ };
  assign _066_ = | { _126_, _122_, _113_, _108_ };
  assign _070_ = $signed({ _140_[31:27], _084_[31:5] }) >= (* src = "design.sv:214.42-214.56" *) $signed(32'd32);
  assign _069_ = $signed(_141_) >= (* src = "design.sv:214.76-214.89" *) $signed(32'd32);
  assign _071_ = $signed(accum) >= (* src = "design.sv:250.29-250.43" *) $signed(32'd0);
  assign _074_ = _075_ || (* src = "design.sv:214.27-214.57" *) _070_;
  assign _072_ = _074_ || (* src = "design.sv:214.27-214.71" *) _076_;
  assign _073_ = _072_ || (* src = "design.sv:214.27-214.90" *) _069_;
  assign _075_ = $signed({ _140_[31:27], _084_[31:5] }) < (* src = "design.sv:214.28-214.36" *) $signed(32'd0);
  assign _076_ = $signed(_141_) < (* src = "design.sv:214.62-214.70" *) $signed(32'd0);
  assign _077_ = $signed(_026_) < (* src = "design.sv:226.25-226.41" *) $signed(32'd3);
  assign _078_ = $signed(_027_) < (* src = "design.sv:231.29-231.38" *) $signed(32'd3);
  assign _079_ = $signed(_028_) < (* src = "design.sv:236.33-236.42" *) $signed(32'd3);
  assign _080_ = $signed(_015_) < (* src = "design.sv:263.25-263.36" *) $signed(32'd0);
  assign _081_ = $signed(_032_) < (* src = "design.sv:276.25-276.38" *) $signed(32'd32);
  assign _082_ = $signed(_033_) < (* src = "design.sv:281.29-281.43" *) $signed(32'd32);
  assign _083_ = $signed(_034_) < (* src = "design.sv:292.25-292.40" *) $signed(32'd16);
  assign _085_ = $signed(m) * (* src = "design.sv:192.39-192.44" *) $signed(32'd3);
  assign _086_ = $signed(_085_) * (* src = "design.sv:192.39-192.55" *) $signed(32'd3);
  assign _087_ = $signed(n) * (* src = "design.sv:192.58-192.70" *) $signed(32'd3);
  assign _088_ = $signed({ kernel_q[7], kernel_q[7], kernel_q[7], kernel_q[7], kernel_q[7], kernel_q[7], kernel_q[7], kernel_q[7], kernel_q }) * (* src = "design.sv:222.38-222.57" *) $signed({ 8'h00, _018_ });
  assign _089_ = $signed(accum) * (* src = "design.sv:251.41-251.56" *) $signed(32'd257);
  assign _090_ = $signed(_091_) * (* src = "design.sv:253.43-253.59" *) $signed(32'd257);
  assign _091_ = - (* src = "design.sv:253.43-253.53" *) $signed(accum);
  assign _092_ = - (* src = "design.sv:253.39-253.79" *) $signed({ _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63], _030_[63:16] });
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) image_addr_valid <= 1'h0;
    else image_addr_valid <= _007_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) image_data_ready <= 1'h0;
    else image_data_ready <= _008_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) kernel_data_ready <= 1'h0;
    else kernel_data_ready <= _010_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) bias_addr_valid <= 1'h0;
    else bias_addr_valid <= _001_;
  (* src = "design.sv:98.5-308.8" *)
  always @(posedge clk, posedge rst)
    if (rst) bias_data_ready <= 1'h0;
    else bias_data_ready <= _002_;
  function [7:0] _239_;
    input [7:0] a;
    input [15:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:215.25-219.32" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _239_ = b[7:0];
      2'b1?:
        _239_ = b[15:8];
      default:
        _239_ = a;
    endcase
  endfunction
  assign _093_ = _239_(image_b_q, { image_r_q, image_g_q }, { _095_, _094_ });
  assign _094_ = c == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:215.25-219.32" *) 32'd1;
  assign _095_ = ! (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:215.25-219.32" *) c;
  assign _096_ = _073_ ? (* full_case = 32'd1 *) (* src = "design.sv:214.25-214.91|design.sv:214.21-224.24" *) 8'hxx : _093_;
  assign _018_ = _097_ ? (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) _096_ : 8'hxx;
  assign _101_ = bias_data_valid ? (* src = "design.sv:151.25-151.40|design.sv:151.21-156.24" *) 1'h1 : 1'h0;
  assign _002_ = _102_ ? (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) _101_ : 1'h0;
  assign _001_ = _103_ ? (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 1'h1 : 1'h0;
  assign _104_ = kernel_data_valid ? (* src = "design.sv:202.25-202.42|design.sv:202.21-206.24" *) 1'h1 : 1'h0;
  assign _010_ = _105_ ? (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) _104_ : 1'h0;
  assign _106_ = image_data_valid ? (* full_case = 32'd1 *) (* src = "design.sv:185.25-185.41|design.sv:185.21-197.24" *) 1'h1 : 1'h0;
  assign _008_ = _098_ ? (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) _106_ : 1'h0;
  assign _107_ = _073_ ? (* full_case = 32'd1 *) (* src = "design.sv:172.25-172.88|design.sv:172.21-180.24" *) 1'h0 : 1'h1;
  assign _007_ = _100_ ? (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) _107_ : 1'h0;
  function [5:0] _253_;
    input [5:0] a;
    input [71:0] b;
    input [11:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      12'b???????????1:
        _253_ = b[5:0];
      12'b??????????1?:
        _253_ = b[11:6];
      12'b?????????1??:
        _253_ = b[17:12];
      12'b????????1???:
        _253_ = b[23:18];
      12'b???????1????:
        _253_ = b[29:24];
      12'b??????1?????:
        _253_ = b[35:30];
      12'b?????1??????:
        _253_ = b[41:36];
      12'b????1???????:
        _253_ = b[47:42];
      12'b???1????????:
        _253_ = b[53:48];
      12'b??1?????????:
        _253_ = b[59:54];
      12'b?1??????????:
        _253_ = b[65:60];
      12'b1???????????:
        _253_ = b[71:66];
      default:
        _253_ = a;
    endcase
  endfunction
  assign _014_ = _253_(6'h00, { _125_, _124_, _123_, 6'h05, _121_, _119_, _117_, _116_, 6'h0c, _112_, _109_, 6'hxx }, { _126_, _103_, _102_, _122_, _100_, _098_, _105_, _097_, _099_, _113_, _110_, _108_ });
  assign _109_ = _083_ ? (* full_case = 32'd1 *) (* src = "design.sv:292.25-292.40|design.sv:292.21-297.24" *) 6'h01 : 6'h0e;
  assign _111_ = _082_ ? (* full_case = 32'd1 *) (* src = "design.sv:281.29-281.43|design.sv:281.25-287.28" *) 6'h04 : 6'h0d;
  assign _112_ = _081_ ? (* full_case = 32'd1 *) (* src = "design.sv:276.25-276.38|design.sv:276.21-288.24" *) 6'h04 : _111_;
  assign _114_ = _079_ ? (* full_case = 32'd1 *) (* src = "design.sv:236.33-236.42|design.sv:236.29-241.32" *) 6'h05 : 6'h0b;
  assign _115_ = _078_ ? (* full_case = 32'd1 *) (* src = "design.sv:231.29-231.38|design.sv:231.25-242.28" *) 6'h05 : _114_;
  assign _116_ = _077_ ? (* full_case = 32'd1 *) (* src = "design.sv:226.25-226.41|design.sv:226.21-243.24" *) 6'h05 : _115_;
  assign _117_ = kernel_data_valid ? (* src = "design.sv:202.25-202.42|design.sv:202.21-206.24" *) 6'h0a : 6'hxx;
  assign _118_ = kernel_addr_ready ? (* src = "design.sv:195.29-195.46|design.sv:195.25-196.50" *) 6'h09 : 6'hxx;
  assign _119_ = image_data_valid ? (* full_case = 32'd1 *) (* src = "design.sv:185.25-185.41|design.sv:185.21-197.24" *) _118_ : 6'hxx;
  assign _120_ = image_addr_ready ? (* src = "design.sv:178.29-178.45|design.sv:178.25-179.49" *) 6'h07 : 6'hxx;
  assign _121_ = _073_ ? (* full_case = 32'd1 *) (* src = "design.sv:172.25-172.88|design.sv:172.21-180.24" *) 6'h0a : _120_;
  assign _123_ = bias_data_valid ? (* src = "design.sv:151.25-151.40|design.sv:151.21-156.24" *) 6'h04 : 6'hxx;
  assign _124_ = bias_addr_ready ? (* src = "design.sv:146.25-146.40|design.sv:146.21-147.46" *) 6'h03 : 6'hxx;
  assign _125_ = start ? (* src = "design.sv:135.25-135.30|design.sv:135.21-138.24" *) 6'h01 : 6'hxx;
  assign _105_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h09;
  assign _102_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h03;
  assign _127_ = _073_ ? (* full_case = 32'd1 *) (* src = "design.sv:214.25-214.91|design.sv:214.21-224.24" *) 64'hxxxxxxxxxxxxxxxx : _025_;
  function [63:0] _271_;
    input [63:0] a;
    input [127:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _271_ = b[63:0];
      2'b1?:
        _271_ = b[127:64];
      default:
        _271_ = a;
    endcase
  endfunction
  assign _000_ = _271_(64'hxxxxxxxxxxxxxxxx, { 64'h0000000000000000, _127_ }, { _122_, _097_ });
  assign _128_ = _077_ ? (* full_case = 32'd1 *) (* src = "design.sv:226.25-226.41|design.sv:226.21-243.24" *) _026_ : 32'd0;
  function [31:0] _273_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _273_ = b[31:0];
      2'b1?:
        _273_ = b[63:32];
      default:
        _273_ = a;
    endcase
  endfunction
  assign _003_ = _273_(32'hxxxxxxxx, { 32'h00000000, _128_ }, { _122_, _097_ });
  assign _129_ = _078_ ? (* full_case = 32'd1 *) (* src = "design.sv:231.29-231.38|design.sv:231.25-242.28" *) _027_ : 32'd0;
  assign _130_ = _077_ ? (* full_case = 32'd1 *) (* src = "design.sv:226.25-226.41|design.sv:226.21-243.24" *) 32'hxxxxxxxx : _129_;
  function [31:0] _276_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _276_ = b[31:0];
      2'b1?:
        _276_ = b[63:32];
      default:
        _276_ = a;
    endcase
  endfunction
  assign _012_ = _276_(32'hxxxxxxxx, { 32'h00000000, _130_ }, { _122_, _097_ });
  assign _131_ = _079_ ? (* full_case = 32'd1 *) (* src = "design.sv:236.33-236.42|design.sv:236.29-241.32" *) _028_ : 32'hxxxxxxxx;
  assign _132_ = _078_ ? (* full_case = 32'd1 *) (* src = "design.sv:231.29-231.38|design.sv:231.25-242.28" *) 32'hxxxxxxxx : _131_;
  assign _133_ = _077_ ? (* full_case = 32'd1 *) (* src = "design.sv:226.25-226.41|design.sv:226.21-243.24" *) 32'hxxxxxxxx : _132_;
  function [31:0] _280_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _280_ = b[31:0];
      2'b1?:
        _280_ = b[63:32];
      default:
        _280_ = a;
    endcase
  endfunction
  assign _011_ = _280_(32'hxxxxxxxx, { 32'h00000000, _133_ }, { _122_, _097_ });
  assign _097_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h0a;
  assign _134_ = _081_ ? (* full_case = 32'd1 *) (* src = "design.sv:276.25-276.38|design.sv:276.21-288.24" *) _032_ : 32'd0;
  function [31:0] _283_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _283_ = b[31:0];
      2'b1?:
        _283_ = b[63:32];
      default:
        _283_ = a;
    endcase
  endfunction
  assign _009_ = _283_(32'hxxxxxxxx, { _135_, _134_ }, { _126_, _113_ });
  assign _135_ = start ? (* src = "design.sv:135.25-135.30|design.sv:135.21-138.24" *) 32'd0 : 32'hxxxxxxxx;
  assign _136_ = _082_ ? (* full_case = 32'd1 *) (* src = "design.sv:281.29-281.43|design.sv:281.25-287.28" *) _033_ : 32'd0;
  assign _137_ = _081_ ? (* full_case = 32'd1 *) (* src = "design.sv:276.25-276.38|design.sv:276.21-288.24" *) 32'hxxxxxxxx : _136_;
  function [31:0] _287_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _287_ = b[31:0];
      2'b1?:
        _287_ = b[63:32];
      default:
        _287_ = a;
    endcase
  endfunction
  assign _006_ = _287_(32'hxxxxxxxx, { _135_, _137_ }, { _126_, _113_ });
  assign _138_ = _083_ ? (* full_case = 32'd1 *) (* src = "design.sv:292.25-292.40|design.sv:292.21-297.24" *) _034_ : 32'hxxxxxxxx;
  function [31:0] _289_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _289_ = b[31:0];
      2'b1?:
        _289_ = b[63:32];
      default:
        _289_ = a;
    endcase
  endfunction
  assign _005_ = _289_(32'hxxxxxxxx, { _135_, _138_ }, { _126_, _110_ });
  assign _110_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h0d;
  function [0:0] _291_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _291_ = b[0:0];
      2'b1?:
        _291_ = b[1:1];
      default:
        _291_ = a;
    endcase
  endfunction
  assign _013_ = _291_(1'hx, 2'h2, { _099_, _066_ });
  assign _113_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h0c;
  assign _122_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h04;
  assign _099_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h0b;
  assign _103_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h01;
  assign _098_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h07;
  assign _100_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h05;
  function [0:0] _298_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _298_ = b[0:0];
      2'b1?:
        _298_ = b[1:1];
      default:
        _298_ = a;
    endcase
  endfunction
  assign _004_ = _298_(1'hx, 2'h1, { _126_, _108_ });
  assign _108_ = state == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) 6'h0e;
  assign _126_ = ! (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) state;
  assign _016_ = _080_ ? (* full_case = 32'd1 *) (* src = "design.sv:263.25-263.36|design.sv:263.21-266.48" *) 32'd0 : _015_;
  assign _139_ = _071_ ? (* full_case = 32'd1 *) (* src = "design.sv:250.29-250.43|design.sv:250.25-253.80" *) _029_[47:16] : _092_[31:0];
  assign _017_ = _099_ ? (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) _139_ : 32'hxxxxxxxx;
  assign _015_ = _099_ ? (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0|design.sv:130.13-306.20" *) _031_ : 32'hxxxxxxxx;
  assign { _140_[31:27], _084_[31:5] } = $signed(_019_) - (* src = "design.sv:212.28-212.39" *) $signed(32'd1);
  assign _141_ = $signed(_020_) - (* src = "design.sv:213.28-213.39" *) $signed(32'd1);
  assign _084_[4:0] = 5'h00;
  assign _140_[26:0] = _084_[31:5];
  assign kernel_addr_valid = image_data_ready;
endmodule
