/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "00_conv2d_bias_rom.v:3.1-47.10" *)
module rom_00_conv2d_bias(clk, rst, addr_valid, addr_ready, addr, data_valid, data_ready, data);
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [7:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _08_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _10_;
  (* src = "00_conv2d_bias_rom.v:13.23-13.27" *)
  input [3:0] addr;
  wire [3:0] addr;
  (* src = "00_conv2d_bias_rom.v:12.35-12.45" *)
  output addr_ready;
  wire addr_ready;
  (* src = "00_conv2d_bias_rom.v:11.35-11.45" *)
  input addr_valid;
  wire addr_valid;
  (* src = "00_conv2d_bias_rom.v:7.35-7.38" *)
  input clk;
  wire clk;
  (* src = "00_conv2d_bias_rom.v:18.35-18.39" *)
  output [7:0] data;
  wire [7:0] data;
  (* src = "00_conv2d_bias_rom.v:17.35-17.45" *)
  input data_ready;
  wire data_ready;
  (* src = "00_conv2d_bias_rom.v:16.35-16.45" *)
  output data_valid;
  wire data_valid;
  (* src = "00_conv2d_bias_rom.v:8.35-8.38" *)
  input rst;
  wire rst;
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _11_ (
    .I0(_10_[0]),
    .I1(_09_[3]),
    .I2(_09_[2]),
    .O(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h3b03)
  ) _12_ (
    .I0(_07_[0]),
    .I1(_07_[1]),
    .I2(_07_[2]),
    .I3(_07_[3]),
    .O(_00_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hdc0b)
  ) _13_ (
    .I0(_07_[0]),
    .I1(_07_[2]),
    .I2(_07_[1]),
    .I3(_07_[3]),
    .O(_00_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h05c8)
  ) _14_ (
    .I0(_07_[0]),
    .I1(_07_[2]),
    .I2(_07_[3]),
    .I3(_07_[1]),
    .O(_00_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h00f1)
  ) _15_ (
    .I0(_07_[2]),
    .I1(_07_[0]),
    .I2(_07_[1]),
    .I3(_07_[3]),
    .O(_00_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hd001)
  ) _16_ (
    .I0(_07_[0]),
    .I1(_07_[2]),
    .I2(_07_[1]),
    .I3(_07_[3]),
    .O(_00_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h8001)
  ) _17_ (
    .I0(_07_[0]),
    .I1(_07_[2]),
    .I2(_07_[1]),
    .I3(_07_[3]),
    .O(_00_[7])
  );
  BUFG _18_ (
    .I(_02_),
    .O(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _19_ (
    .C(_05_),
    .CE(_01_),
    .D(_00_[0]),
    .Q(_06_[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _20_ (
    .C(_05_),
    .CE(_01_),
    .D(_00_[1]),
    .Q(_06_[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _21_ (
    .C(_05_),
    .CE(_01_),
    .D(_00_[2]),
    .Q(_06_[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _22_ (
    .C(_05_),
    .CE(_01_),
    .D(_00_[3]),
    .Q(_06_[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _23_ (
    .C(_05_),
    .CE(_01_),
    .D(_00_[4]),
    .Q(_06_[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _24_ (
    .C(_05_),
    .CE(_01_),
    .D(_00_[7]),
    .Q(_06_[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "00_conv2d_bias_rom.v:27.5-46.8|/oss-cad-suite/lib/../share/yosys/xilinx/ff_map.v:42.41-42.97" *)
  FDPE #(
    .INIT(1'hx)
  ) _25_ (
    .C(_05_),
    .CE(1'h1),
    .D(_04_),
    .PRE(_10_[0]),
    .Q(_09_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "00_conv2d_bias_rom.v:27.5-46.8|/oss-cad-suite/lib/../share/yosys/xilinx/ff_map.v:31.41-31.97" *)
  FDCE #(
    .INIT(1'hx)
  ) _26_ (
    .C(_05_),
    .CE(1'h1),
    .CLR(_10_[0]),
    .D(_03_),
    .Q(_08_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'h08f8)
  ) _27_ (
    .I0(_09_[3]),
    .I1(_09_[2]),
    .I2(_08_[0]),
    .I3(_08_[1]),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT4 #(
    .INIT(16'hf222)
  ) _28_ (
    .I0(_09_[3]),
    .I1(_09_[2]),
    .I2(_08_[0]),
    .I3(_08_[1]),
    .O(_04_)
  );
  (* keep = 32'd1 *)
  IBUF _29_ (
    .I(addr[0]),
    .O(_07_[2])
  );
  (* keep = 32'd1 *)
  IBUF _30_ (
    .I(addr[1]),
    .O(_07_[3])
  );
  (* keep = 32'd1 *)
  IBUF _31_ (
    .I(addr[2]),
    .O(_07_[0])
  );
  (* keep = 32'd1 *)
  IBUF _32_ (
    .I(addr[3]),
    .O(_07_[1])
  );
  (* keep = 32'd1 *)
  OBUF _33_ (
    .I(_09_[3]),
    .O(addr_ready)
  );
  (* keep = 32'd1 *)
  IBUF _34_ (
    .I(addr_valid),
    .O(_09_[2])
  );
  (* keep = 32'd1 *)
  IBUF _35_ (
    .I(clk),
    .O(_02_)
  );
  (* keep = 32'd1 *)
  OBUF _36_ (
    .I(_06_[0]),
    .O(data[0])
  );
  (* keep = 32'd1 *)
  OBUF _37_ (
    .I(_06_[1]),
    .O(data[1])
  );
  (* keep = 32'd1 *)
  OBUF _38_ (
    .I(_06_[2]),
    .O(data[2])
  );
  (* keep = 32'd1 *)
  OBUF _39_ (
    .I(_06_[3]),
    .O(data[3])
  );
  (* keep = 32'd1 *)
  OBUF _40_ (
    .I(_06_[4]),
    .O(data[4])
  );
  (* keep = 32'd1 *)
  OBUF _41_ (
    .I(_06_[7]),
    .O(data[5])
  );
  (* keep = 32'd1 *)
  OBUF _42_ (
    .I(_06_[7]),
    .O(data[6])
  );
  (* keep = 32'd1 *)
  OBUF _43_ (
    .I(_06_[7]),
    .O(data[7])
  );
  (* keep = 32'd1 *)
  IBUF _44_ (
    .I(data_ready),
    .O(_08_[1])
  );
  (* keep = 32'd1 *)
  OBUF _45_ (
    .I(_08_[0]),
    .O(data_valid)
  );
  (* keep = 32'd1 *)
  IBUF _46_ (
    .I(rst),
    .O(_10_[0])
  );
  assign _09_[1:0] = _08_;
  assign _00_[6:5] = { _00_[7], _00_[7] };
  assign _10_[2:1] = { _09_[2], _09_[3] };
  assign _06_[6:5] = { _06_[7], _06_[7] };
endmodule
