-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity StreamingMaxPool_hls_0_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in0_V_TVALID : IN STD_LOGIC;
    buf_V_15_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_14_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_13_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_12_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_11_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_10_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_9_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_8_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_7_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_6_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_5_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_4_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_3_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_2_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_1_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_load_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_15_ce0 : OUT STD_LOGIC;
    buf_V_15_we0 : OUT STD_LOGIC;
    buf_V_15_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    zext_ln156 : IN STD_LOGIC_VECTOR (3 downto 0);
    buf_V_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_14_ce0 : OUT STD_LOGIC;
    buf_V_14_we0 : OUT STD_LOGIC;
    buf_V_14_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_13_ce0 : OUT STD_LOGIC;
    buf_V_13_we0 : OUT STD_LOGIC;
    buf_V_13_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_12_ce0 : OUT STD_LOGIC;
    buf_V_12_we0 : OUT STD_LOGIC;
    buf_V_12_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_11_ce0 : OUT STD_LOGIC;
    buf_V_11_we0 : OUT STD_LOGIC;
    buf_V_11_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_10_ce0 : OUT STD_LOGIC;
    buf_V_10_we0 : OUT STD_LOGIC;
    buf_V_10_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_9_ce0 : OUT STD_LOGIC;
    buf_V_9_we0 : OUT STD_LOGIC;
    buf_V_9_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_8_ce0 : OUT STD_LOGIC;
    buf_V_8_we0 : OUT STD_LOGIC;
    buf_V_8_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_7_ce0 : OUT STD_LOGIC;
    buf_V_7_we0 : OUT STD_LOGIC;
    buf_V_7_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_6_ce0 : OUT STD_LOGIC;
    buf_V_6_we0 : OUT STD_LOGIC;
    buf_V_6_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_5_ce0 : OUT STD_LOGIC;
    buf_V_5_we0 : OUT STD_LOGIC;
    buf_V_5_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_4_ce0 : OUT STD_LOGIC;
    buf_V_4_we0 : OUT STD_LOGIC;
    buf_V_4_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_3_ce0 : OUT STD_LOGIC;
    buf_V_3_we0 : OUT STD_LOGIC;
    buf_V_3_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_2_ce0 : OUT STD_LOGIC;
    buf_V_2_we0 : OUT STD_LOGIC;
    buf_V_2_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_1_ce0 : OUT STD_LOGIC;
    buf_V_1_we0 : OUT STD_LOGIC;
    buf_V_1_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buf_V_ce0 : OUT STD_LOGIC;
    buf_V_we0 : OUT STD_LOGIC;
    buf_V_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in0_V_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    in0_V_TREADY : OUT STD_LOGIC );
end;


architecture behav of StreamingMaxPool_hls_0_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln158_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in0_V_TDATA_blk_n : STD_LOGIC;
    signal zext_ln156_cast_fu_552_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal kx_fu_168 : STD_LOGIC_VECTOR (1 downto 0);
    signal kx_2_fu_666_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_kx_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal oldMax_V_fu_172 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_fu_730_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_1_fu_176 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_1_fu_755_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_1_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_2_fu_180 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_2_fu_780_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_2_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_3_fu_184 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_3_fu_805_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_3_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_4_fu_188 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_4_fu_830_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_4_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_5_fu_192 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_5_fu_855_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_5_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_6_fu_196 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_6_fu_880_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_6_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_7_fu_200 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_7_fu_905_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_7_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_8_fu_204 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_8_fu_930_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_8_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_9_fu_208 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_9_fu_955_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_9_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_10_fu_212 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_10_fu_980_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_10_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_11_fu_216 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_11_fu_1005_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_11_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_12_fu_220 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_12_fu_1030_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_12_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_13_fu_224 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_13_fu_1055_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_13_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_14_fu_228 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_14_fu_1080_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_14_load : STD_LOGIC_VECTOR (3 downto 0);
    signal oldMax_V_15_fu_232 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_15_fu_1105_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_oldMax_V_15_load : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln158_1_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_fu_720_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_1_fu_739_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_1_fu_749_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_2_fu_764_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_2_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_3_fu_789_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_3_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_4_fu_814_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_4_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_5_fu_839_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_5_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_6_fu_864_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_6_fu_874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_7_fu_889_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_7_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_8_fu_914_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_8_fu_924_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_9_fu_939_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_9_fu_949_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_10_fu_964_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_10_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_11_fu_989_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_11_fu_999_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_12_fu_1014_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_12_fu_1024_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_13_fu_1039_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_13_fu_1049_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_14_fu_1064_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_14_fu_1074_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channeldata_V_15_fu_1089_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1035_15_fu_1099_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_573 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component StreamingMaxPool_hls_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component StreamingMaxPool_hls_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    kx_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    kx_fu_168 <= kx_2_fu_666_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kx_fu_168 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_10_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_10_fu_212 <= select_ln167_10_fu_980_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_10_fu_212 <= buf_V_10_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_11_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_11_fu_216 <= select_ln167_11_fu_1005_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_11_fu_216 <= buf_V_11_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_12_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_12_fu_220 <= select_ln167_12_fu_1030_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_12_fu_220 <= buf_V_12_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_13_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_13_fu_224 <= select_ln167_13_fu_1055_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_13_fu_224 <= buf_V_13_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_14_fu_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_14_fu_228 <= select_ln167_14_fu_1080_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_14_fu_228 <= buf_V_14_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_15_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_15_fu_232 <= select_ln167_15_fu_1105_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_15_fu_232 <= buf_V_15_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_1_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_1_fu_176 <= select_ln167_1_fu_755_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_1_fu_176 <= buf_V_1_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_2_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_2_fu_180 <= select_ln167_2_fu_780_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_2_fu_180 <= buf_V_2_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_3_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_3_fu_184 <= select_ln167_3_fu_805_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_3_fu_184 <= buf_V_3_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_4_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_4_fu_188 <= select_ln167_4_fu_830_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_4_fu_188 <= buf_V_4_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_5_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_5_fu_192 <= select_ln167_5_fu_855_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_5_fu_192 <= buf_V_5_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_6_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_6_fu_196 <= select_ln167_6_fu_880_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_6_fu_196 <= buf_V_6_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_7_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_7_fu_200 <= select_ln167_7_fu_905_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_7_fu_200 <= buf_V_7_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_8_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_8_fu_204 <= select_ln167_8_fu_930_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_8_fu_204 <= buf_V_8_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_9_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_9_fu_208 <= select_ln167_9_fu_955_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_9_fu_208 <= buf_V_9_load_1;
                end if;
            end if; 
        end if;
    end process;

    oldMax_V_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_573)) then
                if ((icmp_ln158_fu_660_p2 = ap_const_lv1_0)) then 
                    oldMax_V_fu_172 <= select_ln167_fu_730_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oldMax_V_fu_172 <= buf_V_load_1;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)));
    end process;


    ap_condition_573_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
                ap_condition_573 <= (not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_fu_660_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_kx_1_assign_proc : process(ap_CS_fsm_state1, kx_fu_168, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_kx_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_kx_1 <= kx_fu_168;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_10_load_assign_proc : process(ap_CS_fsm_state1, buf_V_10_load_1, ap_loop_init, oldMax_V_10_fu_212)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_10_load <= buf_V_10_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_10_load <= oldMax_V_10_fu_212;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_11_load_assign_proc : process(ap_CS_fsm_state1, buf_V_11_load_1, ap_loop_init, oldMax_V_11_fu_216)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_11_load <= buf_V_11_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_11_load <= oldMax_V_11_fu_216;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_12_load_assign_proc : process(ap_CS_fsm_state1, buf_V_12_load_1, ap_loop_init, oldMax_V_12_fu_220)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_12_load <= buf_V_12_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_12_load <= oldMax_V_12_fu_220;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_13_load_assign_proc : process(ap_CS_fsm_state1, buf_V_13_load_1, ap_loop_init, oldMax_V_13_fu_224)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_13_load <= buf_V_13_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_13_load <= oldMax_V_13_fu_224;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_14_load_assign_proc : process(ap_CS_fsm_state1, buf_V_14_load_1, ap_loop_init, oldMax_V_14_fu_228)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_14_load <= buf_V_14_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_14_load <= oldMax_V_14_fu_228;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_15_load_assign_proc : process(ap_CS_fsm_state1, buf_V_15_load_1, ap_loop_init, oldMax_V_15_fu_232)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_15_load <= buf_V_15_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_15_load <= oldMax_V_15_fu_232;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_1_load_assign_proc : process(ap_CS_fsm_state1, buf_V_1_load_1, ap_loop_init, oldMax_V_1_fu_176)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_1_load <= buf_V_1_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_1_load <= oldMax_V_1_fu_176;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_2_load_assign_proc : process(ap_CS_fsm_state1, buf_V_2_load_1, ap_loop_init, oldMax_V_2_fu_180)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_2_load <= buf_V_2_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_2_load <= oldMax_V_2_fu_180;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_3_load_assign_proc : process(ap_CS_fsm_state1, buf_V_3_load_1, ap_loop_init, oldMax_V_3_fu_184)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_3_load <= buf_V_3_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_3_load <= oldMax_V_3_fu_184;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_4_load_assign_proc : process(ap_CS_fsm_state1, buf_V_4_load_1, ap_loop_init, oldMax_V_4_fu_188)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_4_load <= buf_V_4_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_4_load <= oldMax_V_4_fu_188;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_5_load_assign_proc : process(ap_CS_fsm_state1, buf_V_5_load_1, ap_loop_init, oldMax_V_5_fu_192)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_5_load <= buf_V_5_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_5_load <= oldMax_V_5_fu_192;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_6_load_assign_proc : process(ap_CS_fsm_state1, buf_V_6_load_1, ap_loop_init, oldMax_V_6_fu_196)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_6_load <= buf_V_6_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_6_load <= oldMax_V_6_fu_196;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_7_load_assign_proc : process(ap_CS_fsm_state1, buf_V_7_load_1, ap_loop_init, oldMax_V_7_fu_200)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_7_load <= buf_V_7_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_7_load <= oldMax_V_7_fu_200;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_8_load_assign_proc : process(ap_CS_fsm_state1, buf_V_8_load_1, ap_loop_init, oldMax_V_8_fu_204)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_8_load <= buf_V_8_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_8_load <= oldMax_V_8_fu_204;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_9_load_assign_proc : process(ap_CS_fsm_state1, buf_V_9_load_1, ap_loop_init, oldMax_V_9_fu_208)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_9_load <= buf_V_9_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_9_load <= oldMax_V_9_fu_208;
        end if; 
    end process;


    ap_sig_allocacmp_oldMax_V_load_assign_proc : process(ap_CS_fsm_state1, buf_V_load_1, ap_loop_init, oldMax_V_fu_172)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_oldMax_V_load <= buf_V_load_1;
        else 
            ap_sig_allocacmp_oldMax_V_load <= oldMax_V_fu_172;
        end if; 
    end process;

    buf_V_10_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_10_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_10_ce0 <= ap_const_logic_1;
        else 
            buf_V_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_10_d0 <= 
        channeldata_V_10_fu_964_p4 when (icmp_ln1035_10_fu_974_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_10_load;

    buf_V_10_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_10_we0 <= ap_const_logic_1;
        else 
            buf_V_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_11_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_11_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_11_ce0 <= ap_const_logic_1;
        else 
            buf_V_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_11_d0 <= 
        channeldata_V_11_fu_989_p4 when (icmp_ln1035_11_fu_999_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_11_load;

    buf_V_11_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_11_we0 <= ap_const_logic_1;
        else 
            buf_V_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_12_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_12_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_12_ce0 <= ap_const_logic_1;
        else 
            buf_V_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_12_d0 <= 
        channeldata_V_12_fu_1014_p4 when (icmp_ln1035_12_fu_1024_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_12_load;

    buf_V_12_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_12_we0 <= ap_const_logic_1;
        else 
            buf_V_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_13_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_13_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_13_ce0 <= ap_const_logic_1;
        else 
            buf_V_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_13_d0 <= 
        channeldata_V_13_fu_1039_p4 when (icmp_ln1035_13_fu_1049_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_13_load;

    buf_V_13_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_13_we0 <= ap_const_logic_1;
        else 
            buf_V_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_14_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_14_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_14_ce0 <= ap_const_logic_1;
        else 
            buf_V_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_14_d0 <= 
        channeldata_V_14_fu_1064_p4 when (icmp_ln1035_14_fu_1074_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_14_load;

    buf_V_14_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_14_we0 <= ap_const_logic_1;
        else 
            buf_V_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_15_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_15_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_15_ce0 <= ap_const_logic_1;
        else 
            buf_V_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_15_d0 <= 
        channeldata_V_15_fu_1089_p4 when (icmp_ln1035_15_fu_1099_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_15_load;

    buf_V_15_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_15_we0 <= ap_const_logic_1;
        else 
            buf_V_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_1_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_1_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_1_ce0 <= ap_const_logic_1;
        else 
            buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_1_d0 <= 
        channeldata_V_1_fu_739_p4 when (icmp_ln1035_1_fu_749_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_1_load;

    buf_V_1_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_1_we0 <= ap_const_logic_1;
        else 
            buf_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_2_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_2_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_2_ce0 <= ap_const_logic_1;
        else 
            buf_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_2_d0 <= 
        channeldata_V_2_fu_764_p4 when (icmp_ln1035_2_fu_774_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_2_load;

    buf_V_2_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_2_we0 <= ap_const_logic_1;
        else 
            buf_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_3_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_3_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_3_ce0 <= ap_const_logic_1;
        else 
            buf_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_3_d0 <= 
        channeldata_V_3_fu_789_p4 when (icmp_ln1035_3_fu_799_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_3_load;

    buf_V_3_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_3_we0 <= ap_const_logic_1;
        else 
            buf_V_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_4_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_4_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_4_ce0 <= ap_const_logic_1;
        else 
            buf_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_4_d0 <= 
        channeldata_V_4_fu_814_p4 when (icmp_ln1035_4_fu_824_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_4_load;

    buf_V_4_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_4_we0 <= ap_const_logic_1;
        else 
            buf_V_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_5_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_5_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_5_ce0 <= ap_const_logic_1;
        else 
            buf_V_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_5_d0 <= 
        channeldata_V_5_fu_839_p4 when (icmp_ln1035_5_fu_849_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_5_load;

    buf_V_5_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_5_we0 <= ap_const_logic_1;
        else 
            buf_V_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_6_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_6_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_6_ce0 <= ap_const_logic_1;
        else 
            buf_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_6_d0 <= 
        channeldata_V_6_fu_864_p4 when (icmp_ln1035_6_fu_874_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_6_load;

    buf_V_6_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_6_we0 <= ap_const_logic_1;
        else 
            buf_V_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_7_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_7_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_7_ce0 <= ap_const_logic_1;
        else 
            buf_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_7_d0 <= 
        channeldata_V_7_fu_889_p4 when (icmp_ln1035_7_fu_899_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_7_load;

    buf_V_7_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_7_we0 <= ap_const_logic_1;
        else 
            buf_V_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_8_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_8_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_8_ce0 <= ap_const_logic_1;
        else 
            buf_V_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_8_d0 <= 
        channeldata_V_8_fu_914_p4 when (icmp_ln1035_8_fu_924_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_8_load;

    buf_V_8_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_8_we0 <= ap_const_logic_1;
        else 
            buf_V_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_9_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_9_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_9_ce0 <= ap_const_logic_1;
        else 
            buf_V_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_9_d0 <= 
        channeldata_V_9_fu_939_p4 when (icmp_ln1035_9_fu_949_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_9_load;

    buf_V_9_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_9_we0 <= ap_const_logic_1;
        else 
            buf_V_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_address0 <= zext_ln156_cast_fu_552_p1(4 - 1 downto 0);

    buf_V_ce0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_ce0 <= ap_const_logic_1;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_d0 <= 
        channeldata_V_fu_720_p1 when (icmp_ln1035_fu_724_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_load;

    buf_V_we0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, icmp_ln158_1_fu_1114_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_1_fu_1114_p2 = ap_const_lv1_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            buf_V_we0 <= ap_const_logic_1;
        else 
            buf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    channeldata_V_10_fu_964_p4 <= in0_V_TDATA(43 downto 40);
    channeldata_V_11_fu_989_p4 <= in0_V_TDATA(47 downto 44);
    channeldata_V_12_fu_1014_p4 <= in0_V_TDATA(51 downto 48);
    channeldata_V_13_fu_1039_p4 <= in0_V_TDATA(55 downto 52);
    channeldata_V_14_fu_1064_p4 <= in0_V_TDATA(59 downto 56);
    channeldata_V_15_fu_1089_p4 <= in0_V_TDATA(63 downto 60);
    channeldata_V_1_fu_739_p4 <= in0_V_TDATA(7 downto 4);
    channeldata_V_2_fu_764_p4 <= in0_V_TDATA(11 downto 8);
    channeldata_V_3_fu_789_p4 <= in0_V_TDATA(15 downto 12);
    channeldata_V_4_fu_814_p4 <= in0_V_TDATA(19 downto 16);
    channeldata_V_5_fu_839_p4 <= in0_V_TDATA(23 downto 20);
    channeldata_V_6_fu_864_p4 <= in0_V_TDATA(27 downto 24);
    channeldata_V_7_fu_889_p4 <= in0_V_TDATA(31 downto 28);
    channeldata_V_8_fu_914_p4 <= in0_V_TDATA(35 downto 32);
    channeldata_V_9_fu_939_p4 <= in0_V_TDATA(39 downto 36);
    channeldata_V_fu_720_p1 <= in0_V_TDATA(4 - 1 downto 0);
    icmp_ln1035_10_fu_974_p2 <= "1" when (unsigned(channeldata_V_10_fu_964_p4) > unsigned(ap_sig_allocacmp_oldMax_V_10_load)) else "0";
    icmp_ln1035_11_fu_999_p2 <= "1" when (unsigned(channeldata_V_11_fu_989_p4) > unsigned(ap_sig_allocacmp_oldMax_V_11_load)) else "0";
    icmp_ln1035_12_fu_1024_p2 <= "1" when (unsigned(channeldata_V_12_fu_1014_p4) > unsigned(ap_sig_allocacmp_oldMax_V_12_load)) else "0";
    icmp_ln1035_13_fu_1049_p2 <= "1" when (unsigned(channeldata_V_13_fu_1039_p4) > unsigned(ap_sig_allocacmp_oldMax_V_13_load)) else "0";
    icmp_ln1035_14_fu_1074_p2 <= "1" when (unsigned(channeldata_V_14_fu_1064_p4) > unsigned(ap_sig_allocacmp_oldMax_V_14_load)) else "0";
    icmp_ln1035_15_fu_1099_p2 <= "1" when (unsigned(channeldata_V_15_fu_1089_p4) > unsigned(ap_sig_allocacmp_oldMax_V_15_load)) else "0";
    icmp_ln1035_1_fu_749_p2 <= "1" when (unsigned(channeldata_V_1_fu_739_p4) > unsigned(ap_sig_allocacmp_oldMax_V_1_load)) else "0";
    icmp_ln1035_2_fu_774_p2 <= "1" when (unsigned(channeldata_V_2_fu_764_p4) > unsigned(ap_sig_allocacmp_oldMax_V_2_load)) else "0";
    icmp_ln1035_3_fu_799_p2 <= "1" when (unsigned(channeldata_V_3_fu_789_p4) > unsigned(ap_sig_allocacmp_oldMax_V_3_load)) else "0";
    icmp_ln1035_4_fu_824_p2 <= "1" when (unsigned(channeldata_V_4_fu_814_p4) > unsigned(ap_sig_allocacmp_oldMax_V_4_load)) else "0";
    icmp_ln1035_5_fu_849_p2 <= "1" when (unsigned(channeldata_V_5_fu_839_p4) > unsigned(ap_sig_allocacmp_oldMax_V_5_load)) else "0";
    icmp_ln1035_6_fu_874_p2 <= "1" when (unsigned(channeldata_V_6_fu_864_p4) > unsigned(ap_sig_allocacmp_oldMax_V_6_load)) else "0";
    icmp_ln1035_7_fu_899_p2 <= "1" when (unsigned(channeldata_V_7_fu_889_p4) > unsigned(ap_sig_allocacmp_oldMax_V_7_load)) else "0";
    icmp_ln1035_8_fu_924_p2 <= "1" when (unsigned(channeldata_V_8_fu_914_p4) > unsigned(ap_sig_allocacmp_oldMax_V_8_load)) else "0";
    icmp_ln1035_9_fu_949_p2 <= "1" when (unsigned(channeldata_V_9_fu_939_p4) > unsigned(ap_sig_allocacmp_oldMax_V_9_load)) else "0";
    icmp_ln1035_fu_724_p2 <= "1" when (unsigned(channeldata_V_fu_720_p1) > unsigned(ap_sig_allocacmp_oldMax_V_load)) else "0";
    icmp_ln158_1_fu_1114_p2 <= "1" when (kx_2_fu_666_p2 = ap_const_lv2_2) else "0";
    icmp_ln158_fu_660_p2 <= "1" when (ap_sig_allocacmp_kx_1 = ap_const_lv2_2) else "0";

    in0_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in0_V_TDATA_blk_n <= in0_V_TVALID;
        else 
            in0_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in0_V_TREADY_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln158_fu_660_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln158_fu_660_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in0_V_TREADY <= ap_const_logic_1;
        else 
            in0_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    kx_2_fu_666_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_kx_1) + unsigned(ap_const_lv2_1));
    select_ln167_10_fu_980_p3 <= 
        channeldata_V_10_fu_964_p4 when (icmp_ln1035_10_fu_974_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_10_load;
    select_ln167_11_fu_1005_p3 <= 
        channeldata_V_11_fu_989_p4 when (icmp_ln1035_11_fu_999_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_11_load;
    select_ln167_12_fu_1030_p3 <= 
        channeldata_V_12_fu_1014_p4 when (icmp_ln1035_12_fu_1024_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_12_load;
    select_ln167_13_fu_1055_p3 <= 
        channeldata_V_13_fu_1039_p4 when (icmp_ln1035_13_fu_1049_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_13_load;
    select_ln167_14_fu_1080_p3 <= 
        channeldata_V_14_fu_1064_p4 when (icmp_ln1035_14_fu_1074_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_14_load;
    select_ln167_15_fu_1105_p3 <= 
        channeldata_V_15_fu_1089_p4 when (icmp_ln1035_15_fu_1099_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_15_load;
    select_ln167_1_fu_755_p3 <= 
        channeldata_V_1_fu_739_p4 when (icmp_ln1035_1_fu_749_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_1_load;
    select_ln167_2_fu_780_p3 <= 
        channeldata_V_2_fu_764_p4 when (icmp_ln1035_2_fu_774_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_2_load;
    select_ln167_3_fu_805_p3 <= 
        channeldata_V_3_fu_789_p4 when (icmp_ln1035_3_fu_799_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_3_load;
    select_ln167_4_fu_830_p3 <= 
        channeldata_V_4_fu_814_p4 when (icmp_ln1035_4_fu_824_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_4_load;
    select_ln167_5_fu_855_p3 <= 
        channeldata_V_5_fu_839_p4 when (icmp_ln1035_5_fu_849_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_5_load;
    select_ln167_6_fu_880_p3 <= 
        channeldata_V_6_fu_864_p4 when (icmp_ln1035_6_fu_874_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_6_load;
    select_ln167_7_fu_905_p3 <= 
        channeldata_V_7_fu_889_p4 when (icmp_ln1035_7_fu_899_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_7_load;
    select_ln167_8_fu_930_p3 <= 
        channeldata_V_8_fu_914_p4 when (icmp_ln1035_8_fu_924_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_8_load;
    select_ln167_9_fu_955_p3 <= 
        channeldata_V_9_fu_939_p4 when (icmp_ln1035_9_fu_949_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_9_load;
    select_ln167_fu_730_p3 <= 
        channeldata_V_fu_720_p1 when (icmp_ln1035_fu_724_p2(0) = '1') else 
        ap_sig_allocacmp_oldMax_V_load;
    zext_ln156_cast_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln156),64));
end behav;
